Controllers/CoursesController.cs
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using elearningdemo.Models.Exceptions;
using ElearningDemo.Models.InputModels;
using ElearningDemo.Models.Services.Application;
using ElearningDemo.Models.ViewModels;
using ELearningDemo.Models.InputModels;
using ELearningDemo.Models.Services.Application;
using Microsoft.AspNetCore.Mvc;

namespace ELearningDemo.Controllers
{
    public class CoursesController : Controller
    {
        private readonly ICachedCourseService courseService;

        public CoursesController(ICachedCourseService courseService)
        {
            this.courseService = courseService;
        }

        public async Task<IActionResult> IsTitleAvailable(string title)
        {
            bool result = await courseService.IsTitleAvailableAsync(title);
            return Json(result);
        }

        public async Task<IActionResult> Index(CoursesListInputModel inputModel)
        {
            ListViewModel<CoursesViewModel> corsi = await courseService.GetCoursesAsync(inputModel);
            CourseListViewModel courseListViewModel = new CourseListViewModel
            {
                Course = corsi,
                Input = inputModel
            };
            ViewData["Title"] = "Catalogo corsi";
            return View(courseListViewModel);
        }

        public async Task<IActionResult> Detail(int id)
        {
            CourseDetailViewModel corso = await courseService.GetCourseAsync(id);
            ViewData["Title"] = corso.Title;
            return View(corso);
        }

        public IActionResult Create()
        {
            ViewData["Title"] = "Nuovo Corso";
            var inputModel = new CourseCreateInputModel();
            return View(inputModel);
        }
        
        [HttpPost]
        public async Task<IActionResult> Create(CourseCreateInputModel inputModel)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    CourseDetailViewModel courseId = await courseService.CreateCourseAsync(inputModel);
                    return RedirectToAction(nameof(Index));
                }
                catch (CourseTitleNotAvalaibleException)
                {
                    ModelState.AddModelError(nameof(CourseDetailViewModel.Title), "Il titolo del corso già esiste");
                }
            }
            
            ViewData["Title"] = "Nuovo Corso";
            return View(inputModel);
        }
    }
}

Controllers/MapController.cs
using Microsoft.AspNetCore.Mvc;

namespace ElearningDemo.Controllers
{
    public class MapController : Controller
    {
        public IActionResult Index()
        {
            ViewData["Title"] = "Mappa";
            return View();
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewData["Title"]</title>
    <environment exclude="Development">
        <!-- CSS only -->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
    </environment>
    <environment include="Development">
        <link rel="stylesheet" href="~/lib/twitter-bootstrap/css/bootstrap.min.css">
        <link rel="stylesheet" href="~/lib/font-awesome/css/all.min.css">
        <!--Da Cancellare-->
        <link rel="stylesheet" href="https://unpkg.com/leaflet@1.7.1/dist/leaflet.css"
        integrity="sha512-xodZBNTC5n17Xt2atTPuE1HxjVMSvLVW9ocqUKLsCC5CXdbqCmblAshOMAS6/keqq/sMZMZ19scR4PsZChSR7A=="
        crossorigin=""/>
    </environment>
    <link rel="stylesheet" href="~/style.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <div class="container-fluid">
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        <li class="nav-item">
                            <a class="nav-link" aria-current="page" asp-action="Index" asp-controller="Home">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" aria-current="page" asp-action="Index" asp-controller="Courses">Catalogo Corsi</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" aria-current="page" asp-action="Index" asp-controller="Map">Mappa</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container-lg">
        @RenderBody()
    </div>
    
    <footer class="container-fluid">
         <p>Contattaci al numero...</p>
    </footer>
    <environment include="Development">
        <script src="~/lib/jquery/jquery.min.js"></script>
        <script src="~/lib/twitter-bootstrap/js/bootstrap.bundle.min.js"></script>
        <script src="~/lib/font-awesome/js/all.min.js"></script>
        <!--Da cancellare-->
        <script src="https://unpkg.com/leaflet@1.7.1/dist/leaflet.js"
            integrity="sha512-XQoYMqMTK8LvdxXYG3nZ448hOEQiglfqkJs1NOQV44cWnUrBc8PkAOcXy20w0vlaXaVUearIOBhiXZ5V3ynxwA=="
            crossorigin=""></script>
    </environment>
    <environment exclude="Development">
       <!-- JavaScript Bundle with Popper -->
       <script src="https://cdn.jsdelivr.net/npm/jquery@3.6.0/dist/jquery.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js" integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf" crossorigin="anonymous"></script>
        <script src="https://kit.fontawesome.com/14e5841d57.js" crossorigin="anonymous"></script> 
    </environment>

    <!-- Client Validation -->
    
    
    @RenderSection("Script", required: false)
    @RenderSection("ScriptMap", required: false)
</body>
</html>

Views/Shared/_Map.cshtml
<script>
        var latitudine = 41.95072;
        var longitudine = 12.15279;
        var map = L.map('demoMap').setView([latitudine, longitudine], 100);
        L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{
            attribution: '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors'
        }).addTo(map);
        L.control.scale().addTo(map);
        var marker = L.marker([latitudine, longitudine]).bindPopup('My House').addTo(map);

        function CambioCoordinate()
        {
            map.removeLayer(marker)
            latitudine = 41.91063;
            longitudine = 12.49304;
            map.setView([latitudine, longitudine], 16);
            L.marker([latitudine, longitudine]).bindPopup('Posteggio Taxi').addTo(map);
        }
        function CasaMia()
        {
            navigator.permissions.query({name:'geolocation'})
                .then(function(permissionStatus) {
                    console.log('geolocation permission state is ', permissionStatus.state);
                    permissionStatus.onchange = function() {
                    console.log('geolocation permission state has changed to ', this.state);
                    };
            });
            if (navigator.geolocation) 
            {
                navigator.geolocation.getCurrentPosition(showPosition, showError);
            } 
            else 
            {
                x.innerHTML = "Geolocation is not supported by this browser.";
            }
        }       

        function showPosition(position)
        {
            map.removeLayer(marker)
            latitudine = parseFloat(position.coords.latitude);
            longitudine = parseFloat(position.coords.longitude);
            map.setView([latitudine, longitudine], 16);
            L.marker([latitudine, longitudine]).bindPopup('Casa Mia').addTo(map);
        }

        function showError(error)
            {
                switch(error.code) 
                {
                    case error.PERMISSION_DENIED:
                        alert("User denied the request for Geolocation.");
                        break;
                    case error.POSITION_UNAVAILABLE:
                        alert("Location information is unavailable.");
                        break;
                    case error.TIMEOUT:
                        alert("The request to get user location timed out.");
                        break;
                    case error.UNKNOWN_ERROR:
                        alert("An unknown error occurred.");
                        break;
                }
            }
    </script>

Views/Shared/_Validation.cshtml
<environment include="Development">
    <script src="~/lib/jquery-validate/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validate/additional-methods.min.js"></script>
    <script src="~/lib/jquery-validate/localization/methods_it.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
</environment>
<environment exclude="Development">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.2/jquery.validate.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.2/additional-methods.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.2/localization/messages_it.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validation-unobtrusive/3.2.12/jquery.validate.unobtrusive.min.js"></script>
</environment>